name: Build Ipe on MacOS with ARM processor
on: workflow_dispatch
jobs:
  Build:
    runs-on: macos-latest
    env:
      OSXTARGET: -mmacosx-version-min=11.00 -target arm64-apple-macos11
      IPECONFIGMAK: macos-manual.mak
      IPEQVORONOI: 1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dmgbuild
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip3 install dmgbuild
      - name: Download dependencies
        run: |
          wget https://github.com/otfried/osx-ipe/releases/download/2024.02.25/osxlibs-arm.tar.gz
          tar xzf osxlibs-arm.tar.gz
      - name: Compile
        run: |
          export IPEDEPS=`pwd`/osxlibs
          cd src
          make -j
          make app
          make dependencies
      - name: Sign
        run: |
          codesign --force --deep -s - build/Ipe.app
          codesign --force --deep -s - build/IpePresenter.app
      - name: Build dmgs
        run: |
          VERSION=`grep -E -o "^IPEVERS.*$" src/config.mak | grep -E -o "[0-9.]+"`
          echo "Ipe version is $VERSION"
          source venv/bin/activate
          dmgbuild -s src/ipe/dmg.py "Ipe $VERSION" ipe-$VERSION-mac-arm.dmg
          dmgbuild -s src/ipe/dmg.py -D app=build/IpePresenter.app \
            "IpePresenter $VERSION" ipepresenter-$VERSION-mac-arm.dmg
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: ipe-mac-arm
          path: ipe*.dmg
          retention-days: 2
      - run: 'echo "Status ${{ job.status }}"'
